version: "3.7"

services:
  geoserver:
    build: ./geoserver
    image: tosca/geoserver
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: geoserver_data
        target: /usr/share/geoserver/data_dir
      - /home/ortak/Desktop:/mnt
    environment:
      - GEOSERVER_CSRF_DISABLED=true

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  # api:
  #   build: ./api
  #   image: tosca/api
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - PORT=3000
  #     - MONGO_CONNECTION_STRING=mongodb://db:27017

  # webapp:
  #   build: ./webapp
  #   image: tosca/webapp
  #   ports:
  #     - 80:80

volumes:
  mongodata:
    driver: local
  geoserver_data:
    driver: local
