version: "3.7"

services:
  geoserver:
    build: ./geoserver
    image: tosca/geoserver
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: geoserver_data
        target: /usr/share/geoserver/data_dir

  wpsserver:
    build: https://github.com/digitalcityscience/TOSCA-flask.git#main
    image: tosca/wpsserver
    ports:
      - 5000:5000
    volumes:
      - type: volume
        source: grass
        target: /pywps-flask/grass
      - type: volume
        source: output
        target: /pywps-flask/outputs
      - type: volume
        source: geoserver_data
        target: /pywps-flask/geoserver_data_dir
    environment:
      - GEOSERVER_URL=http://geoserver:8080/
      - GEOSERVER_USERNAME=admin
      - GEOSERVER_PASSWORD=geoserver
      - GRASS_DIR=/pywps-flask/grass

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  api:
    build: ./api
    image: tosca/api
    ports:
      - 3000:3000
    environment:
      - MONGO_CONNECTION_STRING=mongodb://db:27017

  webapp:
    build: ./webapp
    image: tosca/webapp
    ports:
      - 80:80

volumes:
  mongodata:
    driver: local
  geoserver_data:
    driver: local
  grass:
    driver: local
  output:
    driver: local
