services:
  geoserver:
    image: orttak/tosca-geoserver-hh-wasser
    ports:
      - 8080:8080
    volumes:
      - ./data_dir:/usr/share/geoserver/data_dir
      - ./raw_data:/mnt
    environment:
      - GEOSERVER_CSRF_DISABLED=true

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  api-hh:
    image: orttak/tosca-ps-api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_CONNECTION_STRING=mongodb://db:27017

  webapp:
    image: orttak/tosca-ps-webapp
    ports:
      - 80:80
volumes:
  mongodata:
    driver: local
